name: GitHub-Profile-3D-Contrib

on:
  schedule: # Ejecuta una vez al día
    - cron: "0 0 * * *"
  workflow_dispatch: # Permite correrlo manualmente

jobs:
  build:
    runs-on: ubuntu-latest
    name: generate-github-profile-3d-contrib
    steps:
      - uses: actions/checkout@v3
      - uses: yoshi389111/github-profile-3d-contrib@0.7.1
        with:
          username: ${{ github.repository_owner }}
      - name: Commit & Push
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add -A .
          git commit -m "generated"
          git push
